# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skipper < Formula
  desc ""
  homepage "https://github.com/kartverket/skipper"
  version "0.0.1"

  on_macos do
    url "https://github.com/kartverket/skipper/releases/download/v0.0.1/skipper_0.0.1_darwin_all.tar.gz"
    sha256 "fd8a6bd82d79cd3284ee4adccc976af7119f6df51de83dad594264b2a50362bf"

    def install
      bin.install "skipper"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kartverket/skipper/releases/download/v0.0.1/skipper_0.0.1_linux_arm64.tar.gz"
      sha256 "51ffcfae6dfc510be030013692a71ad8fe300a23ab144bbbf6a7c7e7d0860faa"

      def install
        bin.install "skipper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kartverket/skipper/releases/download/v0.0.1/skipper_0.0.1_linux_amd64.tar.gz"
      sha256 "678181d88c9d2d01821e0f8bc098634f487148e94c20fd23902efb9af893ca17"

      def install
        bin.install "skipper"
      end
    end
  end
end
