# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skipper < Formula
  desc ""
  homepage "https://github.com/kartverket/skipper"
  version "0.0.1"

  on_macos do
    url "https://github.com/kartverket/skipper/releases/download/v0.0.1/skipper_0.0.1_darwin_all.tar.gz"
    sha256 "fa27c2838053077d02157cb650196ce8fee23aa3d3af833c4cd75a306f28ef5c"

    def install
      bin.install "skipper"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kartverket/skipper/releases/download/v0.0.1/skipper_0.0.1_linux_arm64.tar.gz"
      sha256 "846a7686a9622baac25d012f6d3f5198ebf067a9b5e1c873ec8c41064feb5cb4"

      def install
        bin.install "skipper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kartverket/skipper/releases/download/v0.0.1/skipper_0.0.1_linux_amd64.tar.gz"
      sha256 "0773ffdccf622e528a4d1d0f57f0159c9664ad4b3dbafa658dca50668cddc587"

      def install
        bin.install "skipper"
      end
    end
  end
end
