# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skipper < Formula
  desc "A CLI for managing all your SKIP needs!"
  homepage "https://github.com/kartverket/skipper"
  version "0.0.2"

  on_macos do
    url "https://github.com/kartverket/skipper/releases/download/v0.0.2/skipper_0.0.2_darwin_all.tar.gz"
    sha256 "d9d282e7217de7651c1393dd28b3f490adf681bc52a40af800204d927a4d5456"

    def install
      bin.install "skipper"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kartverket/skipper/releases/download/v0.0.2/skipper_0.0.2_linux_amd64.tar.gz"
      sha256 "43bea4acc3174fa7c58400b0927861879bb2d65664851a3158ee3afba86a5d65"

      def install
        bin.install "skipper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kartverket/skipper/releases/download/v0.0.2/skipper_0.0.2_linux_arm64.tar.gz"
      sha256 "89bc2de35c9818d79e48f107c16d0be9ffa8e9a7add8e5cb14f651cae558ef36"

      def install
        bin.install "skipper"
      end
    end
  end
end
